services:
  # Backend Node.js application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: streambridge-backend:latest
    container_name: streambridge-backend
    restart: unless-stopped
    ports:
      - "5045:5045"
    environment:
      - NODE_ENV=production
      - PORT=5045
      - LOG_LEVEL=info
      - KAFKA_BROKERS=kafka:9092
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=streambridge
      - RABBITMQ_PASSWORD=streambridge-password
      - RABBITMQ_VHOST=/
      - JWT_SECRET=${JWT_SECRET:-streambridge-jwt-secret-key-change-in-production}
      - ENCRYPT_MESSAGES=true
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-01234567890123456789012345678901}
      - ALLOWED_ORIGINS=http://localhost:8080
      - WEBSOCKET_AUTH_REQUIRED=false
    volumes:
      - backend_logs:/app/logs
    depends_on:
      - kafka
      - rabbitmq
    networks:
      - streambridge-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5045/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Frontend static application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: streambridge-frontend:latest
    container_name: streambridge-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - streambridge-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: streambridge-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # Not exposing ZooKeeper port externally as it's only used within the container network
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - streambridge-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: streambridge-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    # Not exposing Kafka port externally as it's only used within the container network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - streambridge-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: streambridge-kafka-ui
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: streambridge
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - streambridge-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: streambridge-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: streambridge
      RABBITMQ_DEFAULT_PASS: streambridge-password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - streambridge-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: streambridge-prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - streambridge-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: streambridge-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - streambridge-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  streambridge-network:
    driver: bridge

volumes:
  backend_logs:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data: